// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhcwMDjExudLRRPHyaqYxNcP8QRSN1OWc',
    appId: '1:200559132206:web:b3df78ab83f7f31563a9bf',
    messagingSenderId: '200559132206',
    projectId: 'chartvault-9aa0b',
    authDomain: 'chartvault-9aa0b.firebaseapp.com',
    storageBucket: 'chartvault-9aa0b.appspot.com',
    measurementId: 'G-QSPDXP016Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACjbW0jDW-0tLD5mZhcIXzQVrkA_cZU8U',
    appId: '1:200559132206:android:cdafb0a2705cd6e763a9bf',
    messagingSenderId: '200559132206',
    projectId: 'chartvault-9aa0b',
    storageBucket: 'chartvault-9aa0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdVlfr3v8-IBEO78jU_y68EckxHZrQTQ4',
    appId: '1:200559132206:ios:d2ce4d5708f6946863a9bf',
    messagingSenderId: '200559132206',
    projectId: 'chartvault-9aa0b',
    storageBucket: 'chartvault-9aa0b.appspot.com',
    iosBundleId: 'com.example.chartvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdVlfr3v8-IBEO78jU_y68EckxHZrQTQ4',
    appId: '1:200559132206:ios:d2ce4d5708f6946863a9bf',
    messagingSenderId: '200559132206',
    projectId: 'chartvault-9aa0b',
    storageBucket: 'chartvault-9aa0b.appspot.com',
    iosBundleId: 'com.example.chartvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhcwMDjExudLRRPHyaqYxNcP8QRSN1OWc',
    appId: '1:200559132206:web:a8f9281f543293fc63a9bf',
    messagingSenderId: '200559132206',
    projectId: 'chartvault-9aa0b',
    authDomain: 'chartvault-9aa0b.firebaseapp.com',
    storageBucket: 'chartvault-9aa0b.appspot.com',
    measurementId: 'G-WF4W4VHBW2',
  );
}
